//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisModLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtemisModLoader.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunAs.
        /// </summary>
        public static string AdminVerb {
            get {
                return ResourceManager.GetString("AdminVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.*)|*.*.
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.aml)|*.aml.
        /// </summary>
        public static string AMLFilter {
            get {
                return ResourceManager.GetString("AMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://px2owffng8.embed.tal.ki/20121226/artemis-mod-loader-2176572/?viewmark=1.
        /// </summary>
        public static string AMLUpdateURL {
            get {
                return ResourceManager.GetString("AMLUpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.artemis.eochu.com/?page_id=28#/20121018/unofficial-android-client-for-artemis-1988927.
        /// </summary>
        public static string AndroidClientWebsite {
            get {
                return ResourceManager.GetString("AndroidClientWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.log.
        /// </summary>
        public static string ApplicationLogFile {
            get {
                return ResourceManager.GetString("ApplicationLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artemis.ini.
        /// </summary>
        public static string ArtemisINI {
            get {
                return ResourceManager.GetString("ArtemisINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.artemis.eochu.com/Artemis_Upgrade_v1_66.exe.
        /// </summary>
        public static string ArtemisUpdateFileURL {
            get {
                return ResourceManager.GetString("ArtemisUpdateFileURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.661.
        /// </summary>
        public static string ArtemisVersionAtTimeOfRelease {
            get {
                return ResourceManager.GetString("ArtemisVersionAtTimeOfRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.artemis.eochu.com.
        /// </summary>
        public static string ArtemisWebsite {
            get {
                return ResourceManager.GetString("ArtemisWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///.
        /// </summary>
        public static string CRCR {
            get {
                return ResourceManager.GetString("CRCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aml.
        /// </summary>
        public static string DefaultAMLExtension {
            get {
                return ResourceManager.GetString("DefaultAMLExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISS_.
        /// </summary>
        public static string MissPrefix {
            get {
                return ResourceManager.GetString("MissPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://artemiswiki.pbworks.com/w/page/52152707/Mods.
        /// </summary>
        public static string ModsURL {
            get {
                return ResourceManager.GetString("ModsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to russjudge@gmail.com.
        /// </summary>
        public static string MyEmail {
            get {
                return ResourceManager.GetString("MyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\windows\CurrentVersion\App Paths\Artemis.exe.
        /// </summary>
        public static string RegistryInstallLocation {
            get {
                return ResourceManager.GetString("RegistryInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\Software\ArtemisSBS.
        /// </summary>
        public static string RegistryIPAddressLocation {
            get {
                return ResourceManager.GetString("RegistryIPAddressLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress.
        /// </summary>
        public static string RegistryIPAddressLocationValue {
            get {
                return ResourceManager.GetString("RegistryIPAddressLocationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreArtemis.cmd.
        /// </summary>
        public static string RestoreArtemisCmd {
            get {
                return ResourceManager.GetString("RestoreArtemisCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.zip;*.rar;*.gzip;*.7zip;*.tar)|*.zip;*.rar;*.gzip;*.7zip;*.tar.
        /// </summary>
        public static string SupportedCompressedFilesFilter {
            get {
                return ResourceManager.GetString("SupportedCompressedFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vesselData.xml.
        /// </summary>
        public static string vesselData {
            get {
                return ResourceManager.GetString("vesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedailywtf.com.
        /// </summary>
        public static string WTFURL {
            get {
                return ResourceManager.GetString("WTFURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xcopy &quot;{0}\*.*&quot; &quot;{1}&quot; /s /Y /K /R /H /Q.
        /// </summary>
        public static string XcopyCommand {
            get {
                return ResourceManager.GetString("XcopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string XMLExtension {
            get {
                return ResourceManager.GetString("XMLExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.xml)|*.xml.
        /// </summary>
        public static string XMLFilter {
            get {
                return ResourceManager.GetString("XMLFilter", resourceCulture);
            }
        }
    }
}
