//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselDataLibrary.Xml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VesselDataLibrary.Xml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Width.
        /// </summary>
        internal static string ArcWidth {
            get {
                return ResourceManager.GetString("ArcWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back shield.
        /// </summary>
        internal static string BackShield {
            get {
                return ResourceManager.GetString("BackShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Time.
        /// </summary>
        internal static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse File.
        /// </summary>
        internal static string DiffuseFile {
            get {
                return ResourceManager.GetString("DiffuseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ID..
        /// </summary>
        internal static string DuplicateIDFound {
            get {
                return ResourceManager.GetString("DuplicateIDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front shield.
        /// </summary>
        internal static string FrontShield {
            get {
                return ResourceManager.GetString("FrontShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow File.
        /// </summary>
        internal static string GlowFile {
            get {
                return ResourceManager.GetString("GlowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero..
        /// </summary>
        internal static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID should probably greater than or equal to zero..
        /// </summary>
        internal static string HullRaceIDValidation {
            get {
                return ResourceManager.GetString("HullRaceIDValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race name is required..
        /// </summary>
        internal static string HullRaceNameValidation {
            get {
                return ResourceManager.GetString("HullRaceNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal data structure file does not appear to be a proper *.snt file..
        /// </summary>
        internal static string InternalDataFileExtensionValidation {
            get {
                return ResourceManager.GetString("InternalDataFileExtensionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh File.
        /// </summary>
        internal static string MeshFile {
            get {
                return ResourceManager.GetString("MeshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh file does not appear to be a proper *.dxs file..
        /// </summary>
        internal static string MeshFileExtensionValidation {
            get {
                return ResourceManager.GetString("MeshFileExtensionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an image file..
        /// </summary>
        internal static string NotAnImageFile {
            get {
                return ResourceManager.GetString("NotAnImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship size too small or negative.  This should be increased to avoid in-game image clipping..
        /// </summary>
        internal static string PushRadiusValidation {
            get {
                return ResourceManager.GetString("PushRadiusValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale is invalid.  Please increase this value..
        /// </summary>
        internal static string ScaleValidation {
            get {
                return ResourceManager.GetString("ScaleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want the range so short?.
        /// </summary>
        internal static string ShortRange {
            get {
                return ResourceManager.GetString("ShortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular File.
        /// </summary>
        internal static string SpecularFile {
            get {
                return ResourceManager.GetString("SpecularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed is a bit fast.  Are you sure you want to allow this ship to go this fast?.
        /// </summary>
        internal static string TopSpeedFast {
            get {
                return ResourceManager.GetString("TopSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed must be set to a positive value..
        /// </summary>
        internal static string TopSpeedNegative {
            get {
                return ResourceManager.GetString("TopSpeedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed is zero--this ship will not be able to move.  Are you sure of this?.
        /// </summary>
        internal static string TopSpeedZero {
            get {
                return ResourceManager.GetString("TopSpeedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Type is invalid.  Valid types are 0, 1, 2, and 3..
        /// </summary>
        internal static string TorpedoTypeValidation {
            get {
                return ResourceManager.GetString("TorpedoTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate is set mighty fast.  Are you sure you want this fast of turning?.
        /// </summary>
        internal static string TurnRateFast {
            get {
                return ResourceManager.GetString("TurnRateFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate must be set to a positive value..
        /// </summary>
        internal static string TurnRateNegative {
            get {
                return ResourceManager.GetString("TurnRateNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate is set to zero--this ship will not be able to turn.  Are you sure of this?.
        /// </summary>
        internal static string TurnRateZero {
            get {
                return ResourceManager.GetString("TurnRateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief description of the vessel is required..
        /// </summary>
        internal static string VesselDescriptionValidation {
            get {
                return ResourceManager.GetString("VesselDescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Side&quot; which this vessel is on is not among the valid races..
        /// </summary>
        internal static string VesselSideInvalid {
            get {
                return ResourceManager.GetString("VesselSideInvalid", resourceCulture);
            }
        }
    }
}
