//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1360035698_run {
            get {
                object obj = ResourceManager.GetObject("_1360035698_run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------------------------------------------------------
        ///MISSION SCRIPT DOCS FOR ARTEMIS SBS V1.69
        ///12/30/2012
        ///rev 8
        ///
        ///-----------------------------------------------------------------------------
        ///GENERAL NOTES
        ///The mission script system is designed to let anyone create, share, and play
        ///game missions for Artemis.  In the Artemis install folder, there&apos;s a subfolder
        ///called &apos;Dat&apos;.  Inside that is another folder called &apos;Missions&apos;.
        ///
        ///Inside the Missions folder, each mission needs to h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mission_file_docs {
            get {
                return ResourceManager.GetString("mission_file_docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;mission_data version=&quot;1.69&quot;&gt;
        ///	&lt;start&gt;
        ///		&lt;create type=&quot;player&quot; x=&quot;50000&quot; y=&quot;0&quot; z=&quot;50000&quot; name=&quot;Artemis&quot; /&gt;
        ///		&lt;big_message title=&quot;mission title&quot; subtitle1=&quot;by author&quot; subtitle2=&quot;adventure for Artemis 1.7&quot; /&gt;
        ///	&lt;/start&gt;
        ///  
        ///	&lt;event&gt;
        ///	&lt;/event&gt;
        ///
        ///	&lt;event&gt;
        ///		&lt;if_fleet_count comparator=&quot;LESS_EQUAL&quot; value=&quot;0&quot;/&gt;
        ///		&lt;end_mission /&gt;
        ///	&lt;/event&gt;
        ///  
        ///	&lt;event&gt;
        ///		&lt;if_not_exists name=&quot;Artemis&quot;/&gt;
        ///		&lt;end_mission/&gt;
        ///	&lt;/event&gt;
        ///&lt;/mission_data&gt;.
        /// </summary>
        internal static string NewProjectTemplate {
            get {
                return ResourceManager.GetString("NewProjectTemplate", resourceCulture);
            }
        }
    }
}
