//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselDataLibrary.Xml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VesselDataLibrary.Xml.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcWidth.
        /// </summary>
        internal static string ArcWidth {
            get {
                return ResourceManager.GetString("ArcWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        internal static string Caret {
            get {
                return ResourceManager.GetString("Caret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiffuseFile.
        /// </summary>
        internal static string DiffuseFile {
            get {
                return ResourceManager.GetString("DiffuseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dxs.
        /// </summary>
        internal static string DXSExtension {
            get {
                return ResourceManager.GetString("DXSExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlowFile.
        /// </summary>
        internal static string GlowFile {
            get {
                return ResourceManager.GetString("GlowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshFile.
        /// </summary>
        internal static string MeshFile {
            get {
                return ResourceManager.GetString("MeshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PushRadius.
        /// </summary>
        internal static string PushRadius {
            get {
                return ResourceManager.GetString("PushRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .snt.
        /// </summary>
        internal static string SNTExtension {
            get {
                return ResourceManager.GetString("SNTExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecularFile.
        /// </summary>
        internal static string SpecularFile {
            get {
                return ResourceManager.GetString("SpecularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopSpeed.
        /// </summary>
        internal static string TopSpeed {
            get {
                return ResourceManager.GetString("TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurnRate.
        /// </summary>
        internal static string TurnRate {
            get {
                return ResourceManager.GetString("TurnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueID.
        /// </summary>
        internal static string UniqueID {
            get {
                return ResourceManager.GetString("UniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.66.
        /// </summary>
        internal static string VesselDataCurrentVersion {
            get {
                return ResourceManager.GetString("VesselDataCurrentVersion", resourceCulture);
            }
        }
    }
}
