//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisModLoader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFFFF")]
        public global::System.Windows.Media.Color ModManagerColorLight {
            get {
                return ((global::System.Windows.Media.Color)(this["ModManagerColorLight"]));
            }
            set {
                this["ModManagerColorLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#796DEF34")]
        public global::System.Windows.Media.Color ModManagerColorDark {
            get {
                return ((global::System.Windows.Media.Color)(this["ModManagerColorDark"]));
            }
            set {
                this["ModManagerColorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFFFF")]
        public global::System.Windows.Media.Color MissionColorLight {
            get {
                return ((global::System.Windows.Media.Color)(this["MissionColorLight"]));
            }
            set {
                this["MissionColorLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#798A0000")]
        public global::System.Windows.Media.Color MissionColorDark {
            get {
                return ((global::System.Windows.Media.Color)(this["MissionColorDark"]));
            }
            set {
                this["MissionColorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FF9727")]
        public global::System.Windows.Media.Color ModDefinerLight {
            get {
                return ((global::System.Windows.Media.Color)(this["ModDefinerLight"]));
            }
            set {
                this["ModDefinerLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79B9E4FF")]
        public global::System.Windows.Media.Color ModDefinerDark {
            get {
                return ((global::System.Windows.Media.Color)(this["ModDefinerDark"]));
            }
            set {
                this["ModDefinerDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFC00")]
        public global::System.Windows.Media.Color ModSelectorLight {
            get {
                return ((global::System.Windows.Media.Color)(this["ModSelectorLight"]));
            }
            set {
                this["ModSelectorLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79C4BFF8")]
        public global::System.Windows.Media.Color ModSelectorDark {
            get {
                return ((global::System.Windows.Media.Color)(this["ModSelectorDark"]));
            }
            set {
                this["ModSelectorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7900FF10")]
        public global::System.Windows.Media.Color SessionMonitorLight {
            get {
                return ((global::System.Windows.Media.Color)(this["SessionMonitorLight"]));
            }
            set {
                this["SessionMonitorLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFF0D")]
        public global::System.Windows.Media.Color SessionMonitorDark {
            get {
                return ((global::System.Windows.Media.Color)(this["SessionMonitorDark"]));
            }
            set {
                this["SessionMonitorDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79D49696")]
        public global::System.Windows.Media.Color SettingsLight {
            get {
                return ((global::System.Windows.Media.Color)(this["SettingsLight"]));
            }
            set {
                this["SettingsLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79EFEF0C")]
        public global::System.Windows.Media.Color SettingsDark {
            get {
                return ((global::System.Windows.Media.Color)(this["SettingsDark"]));
            }
            set {
                this["SettingsDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#797FF816")]
        public global::System.Windows.Media.Color ActionLight {
            get {
                return ((global::System.Windows.Media.Color)(this["ActionLight"]));
            }
            set {
                this["ActionLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79F29700")]
        public global::System.Windows.Media.Color ActionDark {
            get {
                return ((global::System.Windows.Media.Color)(this["ActionDark"]));
            }
            set {
                this["ActionDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79DFCFF5")]
        public global::System.Windows.Media.Color FileMappingsLight {
            get {
                return ((global::System.Windows.Media.Color)(this["FileMappingsLight"]));
            }
            set {
                this["FileMappingsLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79F28282")]
        public global::System.Windows.Media.Color FileMappingsDark {
            get {
                return ((global::System.Windows.Media.Color)(this["FileMappingsDark"]));
            }
            set {
                this["FileMappingsDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79F5E64B")]
        public global::System.Windows.Media.Color VariationsLight {
            get {
                return ((global::System.Windows.Media.Color)(this["VariationsLight"]));
            }
            set {
                this["VariationsLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#794EA6F2")]
        public global::System.Windows.Media.Color VariationsDark {
            get {
                return ((global::System.Windows.Media.Color)(this["VariationsDark"]));
            }
            set {
                this["VariationsDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79E2F5F5")]
        public global::System.Windows.Media.Color ArtemisINILight {
            get {
                return ((global::System.Windows.Media.Color)(this["ArtemisINILight"]));
            }
            set {
                this["ArtemisINILight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#798DC3E5")]
        public global::System.Windows.Media.Color ArtemisINIDark {
            get {
                return ((global::System.Windows.Media.Color)(this["ArtemisINIDark"]));
            }
            set {
                this["ArtemisINIDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7967A1FC")]
        public global::System.Windows.Media.Color HullRaceLight {
            get {
                return ((global::System.Windows.Media.Color)(this["HullRaceLight"]));
            }
            set {
                this["HullRaceLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79BE5AFC")]
        public global::System.Windows.Media.Color HullRaceDark {
            get {
                return ((global::System.Windows.Media.Color)(this["HullRaceDark"]));
            }
            set {
                this["HullRaceDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#791CF2B0")]
        public global::System.Windows.Media.Color VesselLight {
            get {
                return ((global::System.Windows.Media.Color)(this["VesselLight"]));
            }
            set {
                this["VesselLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79EF9D1C")]
        public global::System.Windows.Media.Color VesselDark {
            get {
                return ((global::System.Windows.Media.Color)(this["VesselDark"]));
            }
            set {
                this["VesselDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFFFF")]
        public global::System.Windows.Media.Color MergeLight {
            get {
                return ((global::System.Windows.Media.Color)(this["MergeLight"]));
            }
            set {
                this["MergeLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79FFFFFF")]
        public global::System.Windows.Media.Color MergeDark {
            get {
                return ((global::System.Windows.Media.Color)(this["MergeDark"]));
            }
            set {
                this["MergeDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7960F260")]
        public global::System.Windows.Media.Color SelectMergeLight {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectMergeLight"]));
            }
            set {
                this["SelectMergeLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#79E87777")]
        public global::System.Windows.Media.Color SelectMergeDark {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectMergeDark"]));
            }
            set {
                this["SelectMergeDark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateRequired {
            get {
                return ((bool)(this["UpdateRequired"]));
            }
            set {
                this["UpdateRequired"] = value;
            }
        }
    }
}
