//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtemisModLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArtemisModLoader.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunAs.
        /// </summary>
        public static string AdminVerb {
            get {
                return ResourceManager.GetString("AdminVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.*)|*.*.
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.aml)|*.aml.
        /// </summary>
        public static string AMLFilter {
            get {
                return ResourceManager.GetString("AMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://artemis.forumchitchat.com/post/artemis-mod-loader-v-3-0-6476535.
        /// </summary>
        public static string AMLUpdateURL {
            get {
                return ResourceManager.GetString("AMLUpdateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.artemis.eochu.com/?page_id=28#/20121018/unofficial-android-client-for-artemis-1988927.
        /// </summary>
        public static string AndroidClientWebsite {
            get {
                return ResourceManager.GetString("AndroidClientWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application.log.
        /// </summary>
        public static string ApplicationLogFile {
            get {
                return ResourceManager.GetString("ApplicationLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcWidth.
        /// </summary>
        public static string ArcWidth {
            get {
                return ResourceManager.GetString("ArcWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09/16/2012.
        /// </summary>
        public static string Artemis1661FileDate {
            get {
                return ResourceManager.GetString("Artemis1661FileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artemis.ini.
        /// </summary>
        public static string ArtemisINI {
            get {
                return ResourceManager.GetString("ArtemisINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.artemis.eochu.com.
        /// </summary>
        public static string ArtemisWebsite {
            get {
                return ResourceManager.GetString("ArtemisWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.
        /// </summary>
        public static string Caret {
            get {
                return ResourceManager.GetString("Caret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///.
        /// </summary>
        public static string CRCR {
            get {
                return ResourceManager.GetString("CRCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleTime.
        /// </summary>
        public static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .aml.
        /// </summary>
        public static string DefaultAMLExtension {
            get {
                return ResourceManager.GetString("DefaultAMLExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependsOn.
        /// </summary>
        public static string DependsOn {
            get {
                return ResourceManager.GetString("DependsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiffuseFile.
        /// </summary>
        public static string DiffuseFile {
            get {
                return ResourceManager.GetString("DiffuseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dxs.
        /// </summary>
        public static string DXSExtension {
            get {
                return ResourceManager.GetString("DXSExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlowFile.
        /// </summary>
        public static string GlowFile {
            get {
                return ResourceManager.GetString("GlowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files(*.jpg;*.gif;*.jpe;*.png;*.bmp;*.dib;*.tif;*.wmf;*.ras;*.eps;*.pcx;*.pcd;*.tga)|*.jpg;*.gif;*.jpe;*.png;*.bmp;*.dib;*.tif;*.wmf;*.ras;*.eps;*.pcx;*.pcd;*.tga.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshFile.
        /// </summary>
        public static string MeshFile {
            get {
                return ResourceManager.GetString("MeshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISS_.
        /// </summary>
        public static string MissPrefix {
            get {
                return ResourceManager.GetString("MissPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModDefinitions\MOD_Stock.aml.
        /// </summary>
        public static string ModStockFile {
            get {
                return ResourceManager.GetString("ModStockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://artemiswiki.pbworks.com/w/page/52152707/Mods.
        /// </summary>
        public static string ModsURL {
            get {
                return ResourceManager.GetString("ModsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to russjudge@gmail.com.
        /// </summary>
        public static string MyEmail {
            get {
                return ResourceManager.GetString("MyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PushRadius.
        /// </summary>
        public static string PushRadius {
            get {
                return ResourceManager.GetString("PushRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\windows\CurrentVersion\App Paths\Artemis.exe.
        /// </summary>
        public static string RegistryInstallLocation {
            get {
                return ResourceManager.GetString("RegistryInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_CURRENT_USER\Software\ArtemisSBS.
        /// </summary>
        public static string RegistryIPAddressLocation {
            get {
                return ResourceManager.GetString("RegistryIPAddressLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPAddress.
        /// </summary>
        public static string RegistryIPAddressLocationValue {
            get {
                return ResourceManager.GetString("RegistryIPAddressLocationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreArtemis.cmd.
        /// </summary>
        public static string RestoreArtemisCmd {
            get {
                return ResourceManager.GetString("RestoreArtemisCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string Side {
            get {
                return ResourceManager.GetString("Side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .snt.
        /// </summary>
        public static string SNTExtension {
            get {
                return ResourceManager.GetString("SNTExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecularFile.
        /// </summary>
        public static string SpecularFile {
            get {
                return ResourceManager.GetString("SpecularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {5E0D29F0-DEC1-440F-B7A0-F16C520394B1}.
        /// </summary>
        public static string StockID {
            get {
                return ResourceManager.GetString("StockID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.zip;*.rar;*.gzip;*.7zip;*.tar)|*.zip;*.rar;*.gzip;*.7zip;*.tar.
        /// </summary>
        public static string SupportedCompressedFilesFilter {
            get {
                return ResourceManager.GetString("SupportedCompressedFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopSpeed.
        /// </summary>
        public static string TopSpeed {
            get {
                return ResourceManager.GetString("TopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorpedoType.
        /// </summary>
        public static string TorpedoType {
            get {
                return ResourceManager.GetString("TorpedoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TurnRate.
        /// </summary>
        public static string TurnRate {
            get {
                return ResourceManager.GetString("TurnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueID.
        /// </summary>
        public static string UniqueID {
            get {
                return ResourceManager.GetString("UniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vesselData.xml.
        /// </summary>
        public static string vesselData {
            get {
                return ResourceManager.GetString("vesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.702.
        /// </summary>
        public static string VesselDataCurrentVersion {
            get {
                return ResourceManager.GetString("VesselDataCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage.
        /// </summary>
        public static string Webpage {
            get {
                return ResourceManager.GetString("Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://thedailywtf.com.
        /// </summary>
        public static string WTFURL {
            get {
                return ResourceManager.GetString("WTFURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xcopy &quot;{0}\*.*&quot; &quot;{1}&quot; /s /Y /K /R /H /Q.
        /// </summary>
        public static string XcopyCommand {
            get {
                return ResourceManager.GetString("XcopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string XMLExtension {
            get {
                return ResourceManager.GetString("XMLExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (*.xml)|*.xml.
        /// </summary>
        public static string XMLFilter {
            get {
                return ResourceManager.GetString("XMLFilter", resourceCulture);
            }
        }
    }
}
