//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMLResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMLResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Artemis Mod Loader.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for information about the program and author and how to check for updates..
        /// </summary>
        public static string AboutToolTip {
            get {
                return ResourceManager.GetString("AboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Mods.
        /// </summary>
        public static string ActivatedModsHeader {
            get {
                return ResourceManager.GetString("ActivatedModsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to activate the Mod onto Artemis.
        /// </summary>
        public static string ActivateModToolTip {
            get {
                return ResourceManager.GetString("ActivateModToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Beam Port.
        /// </summary>
        public static string AddBeamPort {
            get {
                return ResourceManager.GetString("AddBeamPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Broad Type.
        /// </summary>
        public static string AddBroadType {
            get {
                return ResourceManager.GetString("AddBroadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mod that this Mod depends on..
        /// </summary>
        public static string AddDependsOnToolTip {
            get {
                return ResourceManager.GetString("AddDependsOnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Engine Port.
        /// </summary>
        public static string AddEnginePort {
            get {
                return ResourceManager.GetString("AddEnginePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Impulse Point.
        /// </summary>
        public static string AddImpulsePoint {
            get {
                return ResourceManager.GetString("AddImpulsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Maneuver Point.
        /// </summary>
        public static string AddManeuverPoint {
            get {
                return ResourceManager.GetString("AddManeuverPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mission.
        /// </summary>
        public static string AddMission {
            get {
                return ResourceManager.GetString("AddMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Race.
        /// </summary>
        public static string AddRace {
            get {
                return ResourceManager.GetString("AddRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Torpedo Tube Port.
        /// </summary>
        public static string AddTubePort {
            get {
                return ResourceManager.GetString("AddTubePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vessel.
        /// </summary>
        public static string AddVessel {
            get {
                return ResourceManager.GetString("AddVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files installed successfully..
        /// </summary>
        public static string AllFilesInstalled {
            get {
                return ResourceManager.GetString("AllFilesInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already installed.  Cannot install..
        /// </summary>
        public static string AlreadyInstalled {
            get {
                return ResourceManager.GetString("AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis Mod Loader Definition Files.
        /// </summary>
        public static string AML {
            get {
                return ResourceManager.GetString("AML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to apply to the Unofficial Android Client, go into the Artemis Android Client Settings, Advanced settings and set the &quot;Artemis/dat&quot; location.   Note:  Official Android Client cannot currently be modded..
        /// </summary>
        public static string ApplyToAndroid {
            get {
                return ResourceManager.GetString("ApplyToAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc Width.
        /// </summary>
        public static string ArcWidth {
            get {
                return ResourceManager.GetString("ArcWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path used for running Artemis from {0}:.
        /// </summary>
        public static string ArtemisCopyPath {
            get {
                return ResourceManager.GetString("ArtemisCopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The Artemis Extender requires running with Administrative privilege AND only one copy of Artemis should be run at a time..
        /// </summary>
        public static string ArtemisExtenderToolTip {
            get {
                return ResourceManager.GetString("ArtemisExtenderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis configuration (Artemis.INI).
        /// </summary>
        public static string ArtemisINIHeader {
            get {
                return ResourceManager.GetString("ArtemisINIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach your Android to a USB port so that the files can be copied..
        /// </summary>
        public static string AttachAndroid {
            get {
                return ResourceManager.GetString("AttachAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give credit where credit is due..
        /// </summary>
        public static string AuthorValidation {
            get {
                return ResourceManager.GetString("AuthorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back:.
        /// </summary>
        public static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back shield.
        /// </summary>
        public static string BackShield {
            get {
                return ResourceManager.GetString("BackShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission name indeterminate.  Unable to install..
        /// </summary>
        public static string BadMissionName {
            get {
                return ResourceManager.GetString("BadMissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams Ports.
        /// </summary>
        public static string Beams {
            get {
                return ResourceManager.GetString("Beams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have blown up with the following information..
        /// </summary>
        public static string BlowUp1 {
            get {
                return ResourceManager.GetString("BlowUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this problem persists, email the log file located at &quot;{0}\{1}&quot;.
        /// </summary>
        public static string BlowUp2 {
            get {
                return ResourceManager.GetString("BlowUp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the programmer at {0}.
        /// </summary>
        public static string BlowUp3 {
            get {
                return ResourceManager.GetString("BlowUp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broad Type:.
        /// </summary>
        public static string BroadTypeLabel {
            get {
                return ResourceManager.GetString("BroadTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to folder to copy files to..
        /// </summary>
        public static string BrowseToFolder {
            get {
                return ResourceManager.GetString("BrowseToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open a browser to the web page for this Mod.
        /// </summary>
        public static string BrowseToolTip {
            get {
                return ResourceManager.GetString("BrowseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes..
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the install folder for Artemis Spaceship Bridge Simulator..
        /// </summary>
        public static string CannotLocateArtemisInstall {
            get {
                return ResourceManager.GetString("CannotLocateArtemisInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process..
        /// </summary>
        public static string CannotProcess {
            get {
                return ResourceManager.GetString("CannotProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for latest version.
        /// </summary>
        public static string CheckForLatest {
            get {
                return ResourceManager.GetString("CheckForLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name:.
        /// </summary>
        public static string ClassnameLabel {
            get {
                return ResourceManager.GetString("ClassnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commonality should be zero or greater..
        /// </summary>
        public static string CommonalityInvalid {
            get {
                return ResourceManager.GetString("CommonalityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Controls.ini.
        /// </summary>
        public static string ControlsINI {
            get {
                return ResourceManager.GetString("ControlsINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Complete..
        /// </summary>
        public static string CopyComplete {
            get {
                return ResourceManager.GetString("CopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        public static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files to Mod Installation..
        /// </summary>
        public static string CopyingToModInstallation {
            get {
                return ResourceManager.GetString("CopyingToModInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Critical files to Unofficial Android Client (only from active variation).  Note:  Official Android Client cannot currently be modded..
        /// </summary>
        public static string CopyToAndroidTip {
            get {
                return ResourceManager.GetString("CopyToAndroidTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This could mean the mod is corrupted..
        /// </summary>
        public static string CorruptedMod {
            get {
                return ResourceManager.GetString("CorruptedMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compressed file may be corrupt--this can sometimes happen when the host for the file does not allow direct links..
        /// </summary>
        public static string CorruptZipMessage {
            get {
                return ResourceManager.GetString("CorruptZipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing file.  Compressed file may be corrupt..
        /// </summary>
        public static string CorruptZipMessage2 {
            get {
                return ResourceManager.GetString("CorruptZipMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Time.
        /// </summary>
        public static string CycleTime {
            get {
                return ResourceManager.GetString("CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to deactivate this Mod.
        /// </summary>
        public static string DeactivateToolTip {
            get {
                return ResourceManager.GetString("DeactivateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your default browser will open to the web site if the web site is available..
        /// </summary>
        public static string DefaultBrowser {
            get {
                return ResourceManager.GetString("DefaultBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Beam Port.
        /// </summary>
        public static string DeleteBeamPort {
            get {
                return ResourceManager.GetString("DeleteBeamPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Engine Port.
        /// </summary>
        public static string DeleteEnginePort {
            get {
                return ResourceManager.GetString("DeleteEnginePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Impulse Point.
        /// </summary>
        public static string DeleteImpulsePoint {
            get {
                return ResourceManager.GetString("DeleteImpulsePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Maneuver Point.
        /// </summary>
        public static string DeleteManeuverPoint {
            get {
                return ResourceManager.GetString("DeleteManeuverPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Race.
        /// </summary>
        public static string DeleteRace {
            get {
                return ResourceManager.GetString("DeleteRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Torpedo Tube Port.
        /// </summary>
        public static string DeleteTubePort {
            get {
                return ResourceManager.GetString("DeleteTubePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Vessel.
        /// </summary>
        public static string DeleteVessel {
            get {
                return ResourceManager.GetString("DeleteVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends on {0}.
        /// </summary>
        public static string DependsOn {
            get {
                return ResourceManager.GetString("DependsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Mod depends on Mod {0}, which is not currently installed.  Please install and activate {0} before activating this Mod..
        /// </summary>
        public static string DependsOnAPredefined {
            get {
                return ResourceManager.GetString("DependsOnAPredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Mod depends on Mod {0}, which is not currently active.  Please activate {0} before activating this Mod..
        /// </summary>
        public static string DependsOnIsInstalled {
            get {
                return ResourceManager.GetString("DependsOnIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Mod IDs that this Mod requires:.
        /// </summary>
        public static string DependsOnLabel {
            get {
                return ResourceManager.GetString("DependsOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Mod depends on another Mod, which is not currently installed.  If you are unable to determine where to find the dependent Mod, please contact the creator of this Mod to locate it..
        /// </summary>
        public static string DependsOnNotInstalled {
            get {
                return ResourceManager.GetString("DependsOnNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this  Mod requires another mod be activated, put the ID of that other Mod here..
        /// </summary>
        public static string DependsOnToolTip {
            get {
                return ResourceManager.GetString("DependsOnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The depended-on Mod does not appear to be installed..
        /// </summary>
        public static string DependsOnValidation {
            get {
                return ResourceManager.GetString("DependsOnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Mod.
        /// </summary>
        public static string DeployMod {
            get {
                return ResourceManager.GetString("DeployMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description would be useful to add..
        /// </summary>
        public static string DescriptionValidation {
            get {
                return ResourceManager.GetString("DescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffuse File.
        /// </summary>
        public static string DiffuseFile {
            get {
                return ResourceManager.GetString("DiffuseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to download the package and install.
        /// </summary>
        public static string DownloadAndInstallToolTip {
            get {
                return ResourceManager.GetString("DownloadAndInstallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed:.
        /// </summary>
        public static string DownloadFailedLabel {
            get {
                return ResourceManager.GetString("DownloadFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file not found..
        /// </summary>
        public static string DownloadFileNotFound {
            get {
                return ResourceManager.GetString("DownloadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to download the package from the web?.
        /// </summary>
        public static string DownloadQuestion {
            get {
                return ResourceManager.GetString("DownloadQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A download source would be useful for other users to obtain your Mod..
        /// </summary>
        public static string DownloadSourceValidation {
            get {
                return ResourceManager.GetString("DownloadSourceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A web page where users could find information about your Mod would be helpful..
        /// </summary>
        public static string DownloadWebpageValidation {
            get {
                return ResourceManager.GetString("DownloadWebpageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ID..
        /// </summary>
        public static string DuplicateIDFound {
            get {
                return ResourceManager.GetString("DuplicateIDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in default INI Editor..
        /// </summary>
        public static string EditArtemisINI {
            get {
                return ResourceManager.GetString("EditArtemisINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite.
        /// </summary>
        public static string Elite {
            get {
                return ResourceManager.GetString("Elite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy.
        /// </summary>
        public static string Enemy {
            get {
                return ResourceManager.GetString("Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Ports.
        /// </summary>
        public static string EnginePorts {
            get {
                return ResourceManager.GetString("EnginePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning--Installing this Mod will affect your original Artemis configuration..
        /// </summary>
        public static string EXEInstallWarning {
            get {
                return ResourceManager.GetString("EXEInstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Explorer to Mod&apos;s Install folder..
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Package filename.
        /// </summary>
        public static string FilenameIDButton {
            get {
                return ResourceManager.GetString("FilenameIDButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Filename for ID.  It is the next best thing for setting a globally unique ID, when you are NOT the Mod Developer.  The file name will probably be created by the Mod developer and be unique..
        /// </summary>
        public static string FilenameIDToolTip {
            get {
                return ResourceManager.GetString("FilenameIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet AI Commonality:.
        /// </summary>
        public static string FleetAILabel {
            get {
                return ResourceManager.GetString("FleetAILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly.
        /// </summary>
        public static string Friendly {
            get {
                return ResourceManager.GetString("Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front:.
        /// </summary>
        public static string FrontLabel {
            get {
                return ResourceManager.GetString("FrontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front shield.
        /// </summary>
        public static string FrontShield {
            get {
                return ResourceManager.GetString("FrontShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full restoration of your original Artemis configuration will be attempted, but will require Administrative privilege..
        /// </summary>
        public static string FullRestoreWarning {
            get {
                return ResourceManager.GetString("FullRestoreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Unofficial Android Client.
        /// </summary>
        public static string GetAndroid {
            get {
                return ResourceManager.GetString("GetAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get List of Resource Properties for Translating.
        /// </summary>
        public static string GetListOfResources {
            get {
                return ResourceManager.GetString("GetListOfResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow File.
        /// </summary>
        public static string GlowFile {
            get {
                return ResourceManager.GetString("GlowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero..
        /// </summary>
        public static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New GUID.
        /// </summary>
        public static string GUIDButton {
            get {
                return ResourceManager.GetString("GUIDButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarantees a globally unique ID.  Only use if you are the Mod developer..
        /// </summary>
        public static string GUIDToolTip {
            get {
                return ResourceManager.GetString("GUIDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID should probably greater than or equal to zero..
        /// </summary>
        public static string HullRaceIDValidation {
            get {
                return ResourceManager.GetString("HullRaceIDValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race name is required..
        /// </summary>
        public static string HullRaceNameValidation {
            get {
                return ResourceManager.GetString("HullRaceNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string HullRacesHeader {
            get {
                return ResourceManager.GetString("HullRacesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string IDLabel {
            get {
                return ResourceManager.GetString("IDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse Points.
        /// </summary>
        public static string ImpulsePoints {
            get {
                return ResourceManager.GetString("ImpulsePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected vesselData.xml file is an older version and may not be compatible with the current version of Artemis.
        /// </summary>
        public static string IncompatibleVesselDataMessage {
            get {
                return ResourceManager.GetString("IncompatibleVesselDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install anyhow?.
        /// </summary>
        public static string InstallAnyhowQuestion {
            get {
                return ResourceManager.GetString("InstallAnyhowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installed..
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Mods.
        /// </summary>
        public static string InstalledMods {
            get {
                return ResourceManager.GetString("InstalledMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install from PC.
        /// </summary>
        public static string InstallFromPC {
            get {
                return ResourceManager.GetString("InstallFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to install the already downloaded package..
        /// </summary>
        public static string InstallFromPCToolTip {
            get {
                return ResourceManager.GetString("InstallFromPCToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install From Web.
        /// </summary>
        public static string InstallFromWeb {
            get {
                return ResourceManager.GetString("InstallFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Mod..
        /// </summary>
        public static string InstallingMod {
            get {
                return ResourceManager.GetString("InstallingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Mod to current Artemis configuration..
        /// </summary>
        public static string InstallingModMessage {
            get {
                return ResourceManager.GetString("InstallingModMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mod or Mission.
        /// </summary>
        public static string InstallLabel {
            get {
                return ResourceManager.GetString("InstallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis Spaceship Bridge Simulator Install Location:.
        /// </summary>
        public static string InstallLocationLabel {
            get {
                return ResourceManager.GetString("InstallLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal data structure file does not appear to be a proper *.snt file..
        /// </summary>
        public static string InternalDataFileExtensionValidation {
            get {
                return ResourceManager.GetString("InternalDataFileExtensionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal data structure file required..
        /// </summary>
        public static string InternalDataFileRequired {
            get {
                return ResourceManager.GetString("InternalDataFileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Data File:.
        /// </summary>
        public static string InternalDataLabel {
            get {
                return ResourceManager.GetString("InternalDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to present the server IP address for Artemis..
        /// </summary>
        public static string IPToolTip {
            get {
                return ResourceManager.GetString("IPToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is processing....
        /// </summary>
        public static string IsProcessing {
            get {
                return ResourceManager.GetString("IsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string KeysHeader {
            get {
                return ResourceManager.GetString("KeysHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if not known..
        /// </summary>
        public static string LeaveBlankToolTip {
            get {
                return ResourceManager.GetString("LeaveBlankToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading list of files added by Mod..
        /// </summary>
        public static string LoadingListAddedByMod {
            get {
                return ResourceManager.GetString("LoadingListAddedByMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading current list of Artemis files..
        /// </summary>
        public static string LoadingListOfFiles {
            get {
                return ResourceManager.GetString("LoadingListOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loner.
        /// </summary>
        public static string Loner {
            get {
                return ResourceManager.GetString("Loner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maneuver Points.
        /// </summary>
        public static string ManeuverPoints {
            get {
                return ResourceManager.GetString("ManeuverPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is the case, please manually download the package file and specify it next..
        /// </summary>
        public static string ManuallyDownload {
            get {
                return ResourceManager.GetString("ManuallyDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please manually download the file and select it..
        /// </summary>
        public static string ManuallyDownload2 {
            get {
                return ResourceManager.GetString("ManuallyDownload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep source, discard target..
        /// </summary>
        public static string Merge1 {
            get {
                return ResourceManager.GetString("Merge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep target, discard source..
        /// </summary>
        public static string Merge2 {
            get {
                return ResourceManager.GetString("Merge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt..
        /// </summary>
        public static string Merge3 {
            get {
                return ResourceManager.GetString("Merge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should be done when a conflict between vessels or races is encountered?.
        /// </summary>
        public static string MergeInstruction {
            get {
                return ResourceManager.GetString("MergeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge vessels and races from another vesselData.xml file..
        /// </summary>
        public static string MergeToolTip {
            get {
                return ResourceManager.GetString("MergeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh File.
        /// </summary>
        public static string MeshFile {
            get {
                return ResourceManager.GetString("MeshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh file does not appear to be a proper *.dxs file..
        /// </summary>
        public static string MeshFileExtensionValidation {
            get {
                return ResourceManager.GetString("MeshFileExtensionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file: &quot;{0}&quot;.
        /// </summary>
        public static string MissingFileLabel {
            get {
                return ResourceManager.GetString("MissingFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission File:.
        /// </summary>
        public static string MissionFileLabel {
            get {
                return ResourceManager.GetString("MissionFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission files must start with &quot;{0}&quot; and end with &quot;{1}&quot;..
        /// </summary>
        public static string MissionFileStartWith {
            get {
                return ResourceManager.GetString("MissionFileStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Mode ONLY.
        /// </summary>
        public static string MissionModeOnly {
            get {
                return ResourceManager.GetString("MissionModeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Definition.
        /// </summary>
        public static string ModDefinition {
            get {
                return ResourceManager.GetString("ModDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Definition File Creation.
        /// </summary>
        public static string ModDefinitionTitle {
            get {
                return ResourceManager.GetString("ModDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Development Management.
        /// </summary>
        public static string ModDevHeader {
            get {
                return ResourceManager.GetString("ModDevHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Developer.
        /// </summary>
        public static string ModManager {
            get {
                return ResourceManager.GetString("ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string Mods {
            get {
                return ResourceManager.GetString("Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Mod.
        /// </summary>
        public static string NewMod {
            get {
                return ResourceManager.GetString("NewMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Mods are currently installed.  Please first install the Mod you wish to work on..
        /// </summary>
        public static string NoModsInstalled {
            get {
                return ResourceManager.GetString("NoModsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all files could be removed.  Manual removal required..
        /// </summary>
        public static string NotAllRemoved {
            get {
                return ResourceManager.GetString("NotAllRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an image file..
        /// </summary>
        public static string NotAnImageFile {
            get {
                return ResourceManager.GetString("NotAnImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not located in the correct path--it needs to be in the directory of the Mod..
        /// </summary>
        public static string NotInModPath {
            get {
                return ResourceManager.GetString("NotInModPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a mission file..
        /// </summary>
        public static string NotMissionFile {
            get {
                return ResourceManager.GetString("NotMissionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mod.
        /// </summary>
        public static string OpenMod {
            get {
                return ResourceManager.GetString("OpenMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a vesselData.xml file..
        /// </summary>
        public static string OpenVesselData {
            get {
                return ResourceManager.GetString("OpenVesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package download URL:.
        /// </summary>
        public static string PackageDownloadLabel {
            get {
                return ResourceManager.GetString("PackageDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Web Page:.
        /// </summary>
        public static string PackageWebpageLabel {
            get {
                return ResourceManager.GetString("PackageWebpageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Artemis Extender:.
        /// </summary>
        public static string PathToArtemisExtenderLabel {
            get {
                return ResourceManager.GetString("PathToArtemisExtenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Play another Artemis!.
        /// </summary>
        public static string PlayAnotherArtemis {
            get {
                return ResourceManager.GetString("PlayAnotherArtemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Artemis!.
        /// </summary>
        public static string PlayArtemis {
            get {
                return ResourceManager.GetString("PlayArtemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the uninstaller now for this Mod, then press OK..
        /// </summary>
        public static string PleaseRunUninstaller {
            get {
                return ResourceManager.GetString("PleaseRunUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must make a selection..
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify this location..
        /// </summary>
        public static string PleaseSpecifyLocation {
            get {
                return ResourceManager.GetString("PleaseSpecifyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-defined Mods.
        /// </summary>
        public static string PredefinedMods {
            get {
                return ResourceManager.GetString("PredefinedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem installing.
        /// </summary>
        public static string ProblemInstalling {
            get {
                return ResourceManager.GetString("ProblemInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing will continue, but you may want to deactivate this mod and re-install..
        /// </summary>
        public static string ProcessingContinue {
            get {
                return ResourceManager.GetString("ProcessingContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing...Please Stand by....
        /// </summary>
        public static string ProcessingPleaseStandBy {
            get {
                return ResourceManager.GetString("ProcessingPleaseStandBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis Mod Loader is processing..
        /// </summary>
        public static string ProcessingTitle {
            get {
                return ResourceManager.GetString("ProcessingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress:.
        /// </summary>
        public static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship size too small or negative.  This should be increased to avoid in-game image clipping..
        /// </summary>
        public static string PushRadiusValidation {
            get {
                return ResourceManager.GetString("PushRadiusValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Name:.
        /// </summary>
        public static string RaceNameLabel {
            get {
                return ResourceManager.GetString("RaceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to remove all user files, too?.
        /// </summary>
        public static string RemoveAllUserFilesQuestion {
            get {
                return ResourceManager.GetString("RemoveAllUserFilesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove IP Address Entry.
        /// </summary>
        public static string RemoveIPEntry {
            get {
                return ResourceManager.GetString("RemoveIPEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mission.
        /// </summary>
        public static string RemoveMissionToolTip {
            get {
                return ResourceManager.GetString("RemoveMissionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to completely remove this Mod.
        /// </summary>
        public static string RemoveModToolTip {
            get {
                return ResourceManager.GetString("RemoveModToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset complete..
        /// </summary>
        public static string ResetComplete {
            get {
                return ResourceManager.GetString("ResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Artemis to base stock.
        /// </summary>
        public static string ResetToBaseStock {
            get {
                return ResourceManager.GetString("ResetToBaseStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must now be restarted..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring original Artemis configuration..
        /// </summary>
        public static string RestoringOriginalArtemis {
            get {
                return ResourceManager.GetString("RestoringOriginalArtemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try downloading directly from the web site if you have not already done so..
        /// </summary>
        public static string RetryDownload {
            get {
                return ResourceManager.GetString("RetryDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this vesselData.xml file in a new location or with a new name..
        /// </summary>
        public static string SaveAsVesselData {
            get {
                return ResourceManager.GetString("SaveAsVesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Mod.
        /// </summary>
        public static string SaveMod {
            get {
                return ResourceManager.GetString("SaveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Mod Definition File.
        /// </summary>
        public static string SaveModDefinitionFile {
            get {
                return ResourceManager.GetString("SaveModDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this vesselData.xml file.
        /// </summary>
        public static string SaveVesselData {
            get {
                return ResourceManager.GetString("SaveVesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        public static string ScaleLabel {
            get {
                return ResourceManager.GetString("ScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale is invalid.  Please increase this value..
        /// </summary>
        public static string ScaleValidation {
            get {
                return ResourceManager.GetString("ScaleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Diffuse File.
        /// </summary>
        public static string SelectDiffuseFile {
            get {
                return ResourceManager.GetString("SelectDiffuseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Glow File.
        /// </summary>
        public static string SelectGlowFile {
            get {
                return ResourceManager.GetString("SelectGlowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Merge Option.
        /// </summary>
        public static string SelectMergeOption {
            get {
                return ResourceManager.GetString("SelectMergeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mesh File.
        /// </summary>
        public static string SelectMeshFile {
            get {
                return ResourceManager.GetString("SelectMeshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mod.
        /// </summary>
        public static string SelectMod {
            get {
                return ResourceManager.GetString("SelectMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Specular File.
        /// </summary>
        public static string SelectSpecularFile {
            get {
                return ResourceManager.GetString("SelectSpecularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select target to copy the file to..
        /// </summary>
        public static string SelectTarget {
            get {
                return ResourceManager.GetString("SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Address:.
        /// </summary>
        public static string ServerIPLabel {
            get {
                return ResourceManager.GetString("ServerIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Session Count: .
        /// </summary>
        public static string SessionCountLabel {
            get {
                return ResourceManager.GetString("SessionCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Monitor.
        /// </summary>
        public static string SessionMonitorTitle {
            get {
                return ResourceManager.GetString("SessionMonitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Mods are currently active.  
        ///
        ///Should this Mod be dependent on those active Mods?.
        /// </summary>
        public static string SetDependsOnActivated {
            get {
                return ResourceManager.GetString("SetDependsOnActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis Mod Loader Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shields and Performance.
        /// </summary>
        public static string ShieldsAndPerformance {
            get {
                return ResourceManager.GetString("ShieldsAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Size:.
        /// </summary>
        public static string ShipSize {
            get {
                return ResourceManager.GetString("ShipSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want the range so short?.
        /// </summary>
        public static string ShortRange {
            get {
                return ResourceManager.GetString("ShortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side:.
        /// </summary>
        public static string SideLabel {
            get {
                return ResourceManager.GetString("SideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A source file from Mod &quot;{0}&quot; is missing..
        /// </summary>
        public static string SourceNotFoundPrefix {
            get {
                return ResourceManager.GetString("SourceNotFoundPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source of file is required..
        /// </summary>
        public static string SourceValidation {
            get {
                return ResourceManager.GetString("SourceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular File.
        /// </summary>
        public static string SpecularFile {
            get {
                return ResourceManager.GetString("SpecularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed..
        /// </summary>
        public static string SuccessfullyInstalled {
            get {
                return ResourceManager.GetString("SuccessfullyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Files.
        /// </summary>
        public static string SupportedCompressedFiles {
            get {
                return ResourceManager.GetString("SupportedCompressedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports Invasion Mode.
        /// </summary>
        public static string SupportsInvasionMode {
            get {
                return ResourceManager.GetString("SupportsInvasionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target destination of file is required..
        /// </summary>
        public static string TargetValidation {
            get {
                return ResourceManager.GetString("TargetValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mod.
        /// </summary>
        public static string TestMod {
            get {
                return ResourceManager.GetString("TestMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is NOT a recoverable act!!!.
        /// </summary>
        public static string ThisIsNotRecoverable {
            get {
                return ResourceManager.GetString("ThisIsNotRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artemis Mod Loader.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A title for your variation is required..
        /// </summary>
        public static string TitleVariationValidation {
            get {
                return ResourceManager.GetString("TitleVariationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed is a bit fast.  Are you sure you want to allow this ship to go this fast?.
        /// </summary>
        public static string TopSpeedFast {
            get {
                return ResourceManager.GetString("TopSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Speed:.
        /// </summary>
        public static string TopSpeedLabel {
            get {
                return ResourceManager.GetString("TopSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed must be set to a positive value..
        /// </summary>
        public static string TopSpeedNegative {
            get {
                return ResourceManager.GetString("TopSpeedNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top speed is zero--this ship will not be able to move.  Are you sure of this?.
        /// </summary>
        public static string TopSpeedZero {
            get {
                return ResourceManager.GetString("TopSpeedZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Storage.
        /// </summary>
        public static string TorpedoStorage {
            get {
                return ResourceManager.GetString("TorpedoStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Tube Ports.
        /// </summary>
        public static string TorpedoTubes {
            get {
                return ResourceManager.GetString("TorpedoTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Type is invalid.  Valid types are 0, 1, 2, and 3..
        /// </summary>
        public static string TorpedoTypeValidation {
            get {
                return ResourceManager.GetString("TorpedoTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate is set mighty fast.  Are you sure you want this fast of turning?.
        /// </summary>
        public static string TurnRateFast {
            get {
                return ResourceManager.GetString("TurnRateFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Rate:.
        /// </summary>
        public static string TurnRateLabel {
            get {
                return ResourceManager.GetString("TurnRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate must be set to a positive value..
        /// </summary>
        public static string TurnRateNegative {
            get {
                return ResourceManager.GetString("TurnRateNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn rate is set to zero--this ship will not be able to turn.  Are you sure of this?.
        /// </summary>
        public static string TurnRateZero {
            get {
                return ResourceManager.GetString("TurnRateZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling Mod from configuration..
        /// </summary>
        public static string UninstallingEXEMod {
            get {
                return ResourceManager.GetString("UninstallingEXEMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpackaging &quot;{0}&quot;, writing to &quot;{1}&quot;..
        /// </summary>
        public static string Unpackaging {
            get {
                return ResourceManager.GetString("Unpackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpackaging compressed file..
        /// </summary>
        public static string UnpackagingMod {
            get {
                return ResourceManager.GetString("UnpackagingMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Artemis Extender.
        /// </summary>
        public static string UseArtemisExtender {
            get {
                return ResourceManager.GetString("UseArtemisExtender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to deactivate the active variation and activate this variation..
        /// </summary>
        public static string VariationActivate {
            get {
                return ResourceManager.GetString("VariationActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variations.
        /// </summary>
        public static string Variations {
            get {
                return ResourceManager.GetString("Variations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Data.
        /// </summary>
        public static string VesselDataEdit {
            get {
                return ResourceManager.GetString("VesselDataEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brief description of the vessel is required..
        /// </summary>
        public static string VesselDescriptionValidation {
            get {
                return ResourceManager.GetString("VesselDescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels.
        /// </summary>
        public static string VesselsHeader {
            get {
                return ResourceManager.GetString("VesselsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Side&quot; which this vessel is on is not among the valid races..
        /// </summary>
        public static string VesselSideInvalid {
            get {
                return ResourceManager.GetString("VesselSideInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Readme.txt file.
        /// </summary>
        public static string ViewReadMe {
            get {
                return ResourceManager.GetString("ViewReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale Hater.
        /// </summary>
        public static string WhaleHater {
            get {
                return ResourceManager.GetString("WhaleHater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indifferent to Whales.
        /// </summary>
        public static string WhaleIndifferent {
            get {
                return ResourceManager.GetString("WhaleIndifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale Lover.
        /// </summary>
        public static string WhaleLover {
            get {
                return ResourceManager.GetString("WhaleLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, it works on my machine. Must be something wrong with yours. Seal of Approval from.
        /// </summary>
        public static string WTFLabel {
            get {
                return ResourceManager.GetString("WTFLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
